authenticate:
    type:     annotation
    prefix:   /api/v1
    resource: "@AppBundle/Controller/AuthController.php"

index:
    type:     annotation
    resource: "@AppBundle/Controller/DefaultController.php"
